### ISSUE TITLE
Problems creating links from layer

### ISSUE THREAD

**Issue by grabijas** [AequilibraE/qaequilibrae#158]
Hi.  Attempting to use Aequilibra to do traffic assignments for a rail network.  Data for rails is pretty much the same as roads; nodes and links.

Created two simple layers to test creating an Aeq project: 2 nodes and 1 link. When creating the Aeq project the nodes imported correctly but the link did not.  Checked the link file as best I could to make sure it matched column specifications but could not find any issues.  Stumped. 

In section 1.5.2 of the AequilibraE Documentation Release 30/07/2018 there is this paragraph: 

Note: ALL links that cannot be imported due to errors in the SQL insert statements are written to the log file with error message AND the SQL statement itself, and therefore errors in import can be analyzed for redownloading or fixed by re-running the failed SQL statements after manual fixing

Is this feature still available in the plugin?  It would help me fix this problem.  If so how would I find/use this tool?

Thanks much.  Aeq could be a helpful tool for solving rail problems as well.

Gregg
[Tiny.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/4500545/Tiny.zip)

**Comment by pedrocamargo** [comment]
@grabijas  , you can just click in the "logfile"  menu in the tool to see the log generated by AequilibraE.

This issue, however, is NOT due to AequilibraE.  It is a data issue.  Your links are MultiLineString, instead of LineString.

I am also not seeing A and B nodes

Take a look at https://aequilibrae.com/qgis/V.0.6.1/networkpreparation.html

![2020-04-20 10_40_20-Window](https://user-images.githubusercontent.com/7377666/79704216-b8f5c600-82f3-11ea-8283-9b20cd84f3bf.png)

**Comment by grabijas** [comment]
Thanks Pedro, you feedback was helpful in multiple ways.  I've made progress but having some issues structuring the nodes layer to have the centroids at the top and matching the omx matrix.  Is this issues list the best way to communicate?  I think there's also a Google group address out there as well.
Gregg

**Comment by pedrocamargo** [comment]
Yes, there is.  aequilibrae@googlegroups.com
