### ISSUE TITLE
Error exporting .aem to .csv

### ISSUE THREAD

**Issue by Carolimi** [AequilibraE/qaequilibrae#171]
I'm trying to skim through some centroids to get the network distance between a group of nodes. 
1. I've been able to define the centroids and get a skim of the distance saved in .aem format.
2. I've imported it to  AequilibraE  by : Data> Display AequilibraE formats
3. Then, i've exported the matrix to .csv, but the .csv file saved misses the breaks between lines and instead of:
                      row,column,distance
                      1,2,20.42
                      4,7,9.22
                      ....
it's beeing saved as: row,column,distance1,2,20.424,7,9.22

I tried to reeinstall AequilibraE in QGis and change system formats (my Windows was configured to Brazilian number formats), but i'm still getting the .csv in one line and don't know what i'm doing wrong :(

Desktop 
 - OS: Windows 10
 - QGIS Version [3.10 64 bits]
 - AequilibraE Version [0.6.2]

**Comment by pedrocamargo** [comment]
@Carolimi .  This was indeed an issue with the library, and not the GUI (as discussed over e-mail).

The fix is ready and should be merged in the coming days.  Since I have other pull requests waiting for review, the volunteers might not have time to get to this one for a little bit, but it should not take too long.

You can follow it here:
https://github.com/AequilibraE/aequilibrae/pull/219
